---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.1.254:3100/loki/api/v1/push

scrape_configs:
  - job_name: london-b
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          instance: london-b
          __path__: /var/log/*log
      - targets:
          - localhost
        labels:
          job: plex
          instance: london-b
          __path__: /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/*log
      - targets:
          - localhost
        labels:
          job: jellyfin
          instance: london-b
          __path__: /var/log/jellyfin/*log
