grafana_pagerduty_integration_key: ENC[AES256_GCM,data:m+Ag7AyjEXN+Qn1AjgGjtz+/XcDpidjxNmeHlSORDaE=,iv:+cVVS9Yk6W3KFeRZJ7F4K1EASen4HHfPvrVSF/ZVpiE=,tag:3OfxSDV96aFbGTybCWZuuQ==,type:str]
plex_exporter_plex_token: ENC[AES256_GCM,data:oT+cmlY9p9zGOMd7lVe1loyxh/E=,iv:kjU1U3DLlICFIY3l0yw+PWDNH0q6RhBuLMp5vghVmRs=,tag:02x8Uqk8QObwI9in1q3Qxg==,type:str]
octopus_energy_api_key: ENC[AES256_GCM,data:wINFSZO/P1K31AQfsehv69eYPUWJtnIU65MDPg9IfI3y75R3xE9n7g==,iv:kIKnxIwl5e+mBzq8s1FQO922oSrNIO4yJCg7BKrH33I=,tag:4IAsh8KW+01YXf83tITy2A==,type:str]
proxmox_ve_smb_user: ENC[AES256_GCM,data:13dtQg==,iv:aUOadm20b9FpmOxXGINv8KkwsfBavX755U8SmVCxkCQ=,tag:vV5404IKENKHuBkDwC9GvQ==,type:str]
proxmox_ve_smb_password: ENC[AES256_GCM,data:kYegZCZTpEo7,iv:Jm8yMLKQXyaQQPyybhZyAy9bhN4+OjI63f7azOzqF+w=,tag:IIKCI2bsRzer31hF0h4b9g==,type:str]
sops:
    age:
        - recipient: age1r8uh2w2qad2z5sgq9q7l73962q2sp8zz9hdnh6sjuvanxl565vmswn8squ
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQUtHMERKSmpmcmp6UW9u
            WFpXaHI2Nyt3NHc4QWZuT2NxaGJuVUdmeWtNCm91OGloeDJFNHlzL1k1L1V5MTdL
            b29qdTFUYi9WZ1V2NmozVlpjRFZMeFEKLS0tIG5CVTk1amZNNU4rT2JBYm01K1Bl
            Ti9TNjFta0kyRTNrWGVWbGFGeC9CR3cKkdhytnSS+fCMc1FOSZ5WC3dO16Kw+akB
            O69PKWul3WI7kFmcRk8mzlbFqS941tnPbvVaTYP0+GZTgSX1wlhSeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T19:42:19Z"
    mac: ENC[AES256_GCM,data:E5WuwPXt+FwofwAJaCOZj0so4TUBNtQ5J9Swt3Pwd157XBT4PBt65ZHd+gwUOHnyFa7iJlGXN7miMbtx2XZ72cIP2tl0JsO5NOJoLYTFdnK1NbSnrxyESAWnWenONVHILz10Zy3PJqPaN1P9nlME96LBVr/ii/179UJiAEJMxo8=,iv:3P4C1aW94i5FIvtd8yJswN4WRcqF5uuIpBVnFuPEkT4=,tag:Z3WShXsRs4p8xMG0+MJ54Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
