---
host_role: storage
host_description: "Primary storage (ZFS), Docker services"
host_location: "London"

docker_services:
  - nextcloud-aio
  - jellyseerr
  - navidrome
  - slskd
  - miniflux
  - smartctl-exporter
  - plex-exporter

common_ufw_allowed_ports:
  - {port: 32400, proto: tcp, comment: "Plex Media Server"}
  - {port: 6881, proto: tcp, comment: "BitTorrent"}
  - {port: 6881, proto: udp, comment: "BitTorrent"}
