---
# Plex exporter - Plex metrics for Prometheus
# Host: london-b (100.84.65.101)
# Access: http://london-b:9000/metrics

services:
  plex-exporter:
    image: rwejlgaard/plex_exporter:2.0.0
    container_name: prom-plex-exporter
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      PLEX_SERVER: "http://192.168.1.253:32400"
      PLEX_TOKEN: "{{ plex_exporter_plex_token }}"
