# /etc/rc.conf — london-a (FreeBSD)
# Captured 2026-03-22

clear_tmp_enable="YES"
hostname="london-a"
ifconfig_em0="inet 192.168.1.254 netmask 255.255.255.0"
defaultrouter="192.168.1.1"
ifconfig_em0_ipv6="inet6 accept_rtadv"
sshd_enable="YES"
ntpd_enable="YES"
powerd_enable="YES"
moused_nondefault_enable="NO"
# Set dumpdev to "AUTO" to enable crash dumps, "NO" to disable
dumpdev="AUTO"
zfs_enable="YES"
grafana_enable="YES"
prometheus_enable="YES"
node_exporter_enable="YES"
tailscaled_enable="YES"
influxd_enable="NO"
libvirtd_enable="NO"
redis_enable="NO"
postgresql_enable="NO"
node_exporter_listen_address="100.122.219.41:9100"
