---
- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Reload ufw
  community.general.ufw:
    state: reloaded

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
