{
 "title": "Living Room Display",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{server=\"london-b\", mode=\"idle\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drive Temperature",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sum(smartctl_device_temperature) by (device)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "HDD Space",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{server=\"london-b\",mountpoint=\"/hdd\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "node_filesystem_size_bytes{server=\"london-b\",mountpoint=\"/hdd\"} - node_filesystem_avail_bytes{server=\"london-b\",mountpoint=\"/hdd\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "HDD State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_zfs_zpool_state{server=\"london-b\",zpool=\"hdd\", state=\"online\"} > 0",
     "legendFormat": "Online"
    },
    {
     "expr": "node_zfs_zpool_state{server=\"london-b\",zpool=\"hdd\", state=\"degraded\"} > 0",
     "legendFormat": "Degraded"
    },
    {
     "expr": "node_zfs_zpool_state{server=\"london-b\",zpool=\"hdd\", state=\"faulted\"} > 0",
     "legendFormat": "Faulted"
    },
    {
     "expr": "node_zfs_zpool_state{server=\"london-b\",zpool=\"hdd\", state=\"offline\"} > 0",
     "legendFormat": "Offline"
    },
    {
     "expr": "node_zfs_zpool_state{server=\"london-b\",zpool=\"hdd\", state=\"removed\"} > 0",
     "legendFormat": "Removed"
    },
    {
     "expr": "node_zfs_zpool_state{server=\"london-b\",zpool=\"hdd\", state=\"suspended\"} > 0",
     "legendFormat": "Suspended"
    },
    {
     "expr": "node_zfs_zpool_state{server=\"london-b\",zpool=\"hdd\", state=\"unavail\"} > 0",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min((1 - (node_memory_MemAvailable_bytes{server=\"london-b\"} / node_memory_MemTotal_bytes{server=\"london-b\"})) * 100, 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drive Health",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 5 },
   "targets": [
    { "expr": "smartctl_device_smart_status", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "Available Space",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{server=\"london-b\",mountpoint=\"/hdd\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Space",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{server=\"london-b\",mountpoint=\"/hdd\"} - node_filesystem_avail_bytes{server=\"london-b\",mountpoint=\"/hdd\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Activity",
   "type": "table",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "plays_total{user!=\"Rasmus\"}",
     "legendFormat": "User"
    }
   ]
  },
  {
   "title": "Active Streams",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(plays_total{user!=\"Rasmus\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}