{
 "title": "Traffic / SLO",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "SLI",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  (sum(caddy_http_response_size_bytes_count{host=~\".*(pez.solutions|pez.sh)\", code!~\"5.*\"}) / (sum(caddy_http_response_size_bytes_count{host=~\".*(pez.solutions|pez.sh)\"}))) * 100,\n  99.999\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLI by Host",
   "type": "stat",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\n  (\n    sum(\n      label_replace(\n        caddy_http_response_size_bytes_count{host=~\".*(pez.solutions|pez.sh)\", host!~\"(pez.sh|pez.solutions)\", code!~\"5.*\"},\n        \"host_prefix\",\n        \"$1\",\n        \"host\",\n        \"([^.]+)\\\\..*\"\n      )\n    ) by (host_prefix)\n    /\n    sum(\n      label_replace(\n        caddy_http_response_size_bytes_count{host=~\".*(pez.solutions|pez.sh)\", host!~\"(pez.sh|pez.solutions)\"},\n        \"host_prefix\",\n        \"$1\",\n        \"host\",\n        \"([^.]+)\\\\..*\"\n      )\n    ) by (host_prefix)\n  ) * 100,\n  99.999\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic Rate by Service",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 19, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    rate(caddy_http_requests_total{handler!=\"metrics\", host=~\".*(pez.solutions|pez.sh)\"}[$__rate_interval]),\n    \"host_prefix\",\n    \"$1\",\n    \"host\",\n    \"([^.]+)\\\\..*\"\n  )\n) by (host_prefix)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Active Services",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 10 },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    rate(caddy_http_requests_total{handler!=\"metrics\", host=~\".*(pez.solutions|pez.sh)\", host!~\"(pez.sh|pez.solutions)\"}[$__rate_interval]),\n    \"host_prefix\",\n    \"$1\",\n    \"host\",\n    \"([^.]+)\\\\..*\"\n  )\n) by (host_prefix) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Codes (Good)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(caddy_http_response_duration_seconds_count{code!~\"5.*\"}[$__rate_interval]))",
     "legendFormat": "Good"
    }
   ]
  },
  {
   "title": "Response Codes (Bad)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(caddy_http_response_duration_seconds_count{code=~\"5.*\"}[$__rate_interval])) by (code, host) > 0",
     "legendFormat": "{{code}} - {{host}}"
    }
   ]
  }
 ]
}