---
# ZFS scrub scheduling.

- name: Install ZFS scrub cron jobs
  ansible.builtin.cron:
    name: "ZFS scrub {{ item }}"
    minute: "{{ zfs_scrub_minute }}"
    hour: "{{ zfs_scrub_hour }}"
    weekday: "{{ zfs_scrub_weekday }}"
    job: "/sbin/zpool scrub {{ item }}"
    user: root
  loop: "{{ zfs_pools }}"
  when: zfs_scrub_enabled
