---
- name: Restart alloy (Debian)
  ansible.builtin.service:
    name: alloy
    state: restarted
  listen: "Restart alloy (Debian)"

- name: Restart alloy (Alpine)
  ansible.builtin.service:
    name: alloy
    state: restarted
  listen: "Restart alloy (Alpine)"

- name: Restart alloy (FreeBSD)
  ansible.builtin.service:
    name: alloy
    state: restarted
  listen: "Restart alloy (FreeBSD)"
