---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart promtail
  ansible.builtin.systemd:
    name: promtail
    state: restarted

- name: Restart smbd
  ansible.builtin.systemd:
    name: smbd
    state: restarted

- name: Restart transmission
  ansible.builtin.systemd:
    name: transmission-daemon
    state: restarted

- name: Restart vsftpd
  ansible.builtin.systemd:
    name: vsftpd
    state: restarted
